name: Deploy Worker to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy worker
        uses: azure/webapps-deploy@v3
        with:
          app-name: job-platform-worker-3007
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_WORKER }}
